version: '3.7'

services:
  ml-node:
    image: my-mlflow:latest
    container_name: ml-flow-container
    env_file:
      - cfg.env
    # set_PYTHONPATH 
    # run ml script
    command: ["bash", "-c", "source /entrypoint.sh && set_python_env && set_aws_config && get_ml_script
                && python $${MLFLOW_HOME}/main.py --year-arr $${YEAR_ARR}"]
